# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Documents\Programmation\PublicProject\checkFrench\qt_files\dialog_excluded_words.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(489, 669)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ressource/DreamteamLogo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setModal(True)
        self.pushButton_saveAndQuit = QtWidgets.QPushButton(Dialog)
        self.pushButton_saveAndQuit.setGeometry(QtCore.QRect(340, 620, 131, 41))
        self.pushButton_saveAndQuit.setObjectName("pushButton_saveAndQuit")
        self.pushButton_resetChange = QtWidgets.QPushButton(Dialog)
        self.pushButton_resetChange.setGeometry(QtCore.QRect(190, 620, 141, 41))
        self.pushButton_resetChange.setObjectName("pushButton_resetChange")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 461, 601))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget_excludedWords = QtWidgets.QTableWidget(self.frame)
        self.tableWidget_excludedWords.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_excludedWords.setObjectName("tableWidget_excludedWords")
        self.tableWidget_excludedWords.setColumnCount(1)
        self.tableWidget_excludedWords.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_excludedWords.setHorizontalHeaderItem(0, item)
        self.tableWidget_excludedWords.horizontalHeader().setVisible(False)
        self.tableWidget_excludedWords.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_excludedWords.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_excludedWords.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.tableWidget_excludedWords, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tableWidget_excludedWords, self.pushButton_resetChange)
        Dialog.setTabOrder(self.pushButton_resetChange, self.pushButton_saveAndQuit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Liste mots exclus"))
        self.pushButton_saveAndQuit.setText(_translate("Dialog", "Sauvegarder et quitter"))
        self.pushButton_resetChange.setText(_translate("Dialog", "Réinitialiser changements"))
        item = self.tableWidget_excludedWords.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "mots"))
import qt_files.ressource_rc
