# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Documents\Programmation\PublicProject\checkFrench\checkfrench\ui\create_project\create_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_createProject(object):
    def setupUi(self, Dialog_createProject):
        Dialog_createProject.setObjectName("Dialog_createProject")
        Dialog_createProject.resize(655, 143)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog_createProject)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_main = QtWidgets.QVBoxLayout()
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.horizontalLayout_projectName = QtWidgets.QHBoxLayout()
        self.horizontalLayout_projectName.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_projectName.setObjectName("horizontalLayout_projectName")
        self.label_projectName = QtWidgets.QLabel(Dialog_createProject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_projectName.sizePolicy().hasHeightForWidth())
        self.label_projectName.setSizePolicy(sizePolicy)
        self.label_projectName.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_projectName.setObjectName("label_projectName")
        self.horizontalLayout_projectName.addWidget(self.label_projectName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_projectName.addItem(spacerItem)
        self.lineEdit_projectName = QtWidgets.QLineEdit(Dialog_createProject)
        self.lineEdit_projectName.setObjectName("lineEdit_projectName")
        self.horizontalLayout_projectName.addWidget(self.lineEdit_projectName)
        self.horizontalLayout_projectName.setStretch(0, 1)
        self.horizontalLayout_projectName.setStretch(2, 2)
        self.verticalLayout_main.addLayout(self.horizontalLayout_projectName)
        spacerItem1 = QtWidgets.QSpacerItem(466, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_main.addItem(spacerItem1)
        self.horizontalLayout_language = QtWidgets.QHBoxLayout()
        self.horizontalLayout_language.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_language.setObjectName("horizontalLayout_language")
        self.label_language = QtWidgets.QLabel(Dialog_createProject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_language.sizePolicy().hasHeightForWidth())
        self.label_language.setSizePolicy(sizePolicy)
        self.label_language.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_language.setObjectName("label_language")
        self.horizontalLayout_language.addWidget(self.label_language)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_language.addItem(spacerItem2)
        self.comboBox_language = QtWidgets.QComboBox(Dialog_createProject)
        self.comboBox_language.setObjectName("comboBox_language")
        self.horizontalLayout_language.addWidget(self.comboBox_language)
        self.horizontalLayout_language.setStretch(0, 1)
        self.horizontalLayout_language.setStretch(2, 2)
        self.verticalLayout_main.addLayout(self.horizontalLayout_language)
        spacerItem3 = QtWidgets.QSpacerItem(466, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_main.addItem(spacerItem3)
        self.horizontalLayout_create = QtWidgets.QHBoxLayout()
        self.horizontalLayout_create.setObjectName("horizontalLayout_create")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_create.addItem(spacerItem4)
        self.pushButton_create = QtWidgets.QPushButton(Dialog_createProject)
        self.pushButton_create.setObjectName("pushButton_create")
        self.horizontalLayout_create.addWidget(self.pushButton_create)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_create.addItem(spacerItem5)
        self.verticalLayout_main.addLayout(self.horizontalLayout_create)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_main.addItem(spacerItem6)
        self.verticalLayout_main.setStretch(5, 2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_main)

        self.retranslateUi(Dialog_createProject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_createProject)

    def retranslateUi(self, Dialog_createProject):
        _translate = QtCore.QCoreApplication.translate
        Dialog_createProject.setWindowTitle(_translate("Dialog_createProject", "Create Project"))
        self.label_projectName.setText(_translate("Dialog_createProject", "Project name"))
        self.label_language.setText(_translate("Dialog_createProject", "Language"))
        self.pushButton_create.setText(_translate("Dialog_createProject", "Create"))
