# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Documents\Programmation\PublicProject\checkFrench\qt\confirm_exit\confirm_exit.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(503, 160)
        Dialog.setMinimumSize(QtCore.QSize(503, 160))
        Dialog.setMaximumSize(QtCore.QSize(503, 160))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ressource/DreamteamLogo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.label_messageSecondPart = QtWidgets.QLabel(Dialog)
        self.label_messageSecondPart.setGeometry(QtCore.QRect(10, 50, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_messageSecondPart.setFont(font)
        self.label_messageSecondPart.setAlignment(QtCore.Qt.AlignCenter)
        self.label_messageSecondPart.setObjectName("label_messageSecondPart")
        self.label_messageFirstPart = QtWidgets.QLabel(Dialog)
        self.label_messageFirstPart.setGeometry(QtCore.QRect(10, 10, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_messageFirstPart.setFont(font)
        self.label_messageFirstPart.setAlignment(QtCore.Qt.AlignCenter)
        self.label_messageFirstPart.setObjectName("label_messageFirstPart")
        self.pushButton_QuitWithoutSaving = QtWidgets.QPushButton(Dialog)
        self.pushButton_QuitWithoutSaving.setGeometry(QtCore.QRect(270, 100, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_QuitWithoutSaving.setFont(font)
        self.pushButton_QuitWithoutSaving.setObjectName("pushButton_QuitWithoutSaving")
        self.pushButton_saveAndQuit = QtWidgets.QPushButton(Dialog)
        self.pushButton_saveAndQuit.setGeometry(QtCore.QRect(10, 100, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_saveAndQuit.setFont(font)
        self.pushButton_saveAndQuit.setAutoDefault(True)
        self.pushButton_saveAndQuit.setObjectName("pushButton_saveAndQuit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "DreamTeamTrad - FautesCheck - Sauvegarder termes ?"))
        self.label_messageSecondPart.setText(_translate("Dialog", "Que faire ?"))
        self.label_messageFirstPart.setText(_translate("Dialog", "Des termes n\'ont pas été sauvegardés sur le google sheet."))
        self.pushButton_QuitWithoutSaving.setText(_translate("Dialog", "Quitter sans sauvegarder"))
        self.pushButton_saveAndQuit.setText(_translate("Dialog", "Sauvegarder et quitter"))
import qt.ressource_rc
