# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Documents\Programmation\PublicProject\checkFrench\rawtextcheck\ui\delete_project\delete_project.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_deleteProject(object):
    def setupUi(self, Dialog_deleteProject):
        Dialog_deleteProject.setObjectName("Dialog_deleteProject")
        Dialog_deleteProject.resize(655, 143)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog_deleteProject)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_main = QtWidgets.QVBoxLayout()
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.horizontalLayout_projectName = QtWidgets.QHBoxLayout()
        self.horizontalLayout_projectName.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_projectName.setObjectName("horizontalLayout_projectName")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_projectName.addItem(spacerItem)
        self.label_projectName = QtWidgets.QLabel(Dialog_deleteProject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_projectName.sizePolicy().hasHeightForWidth())
        self.label_projectName.setSizePolicy(sizePolicy)
        self.label_projectName.setText("LABEL_PROJECT_NAME")
        self.label_projectName.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_projectName.setObjectName("label_projectName")
        self.horizontalLayout_projectName.addWidget(self.label_projectName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_projectName.addItem(spacerItem1)
        self.verticalLayout_main.addLayout(self.horizontalLayout_projectName)
        spacerItem2 = QtWidgets.QSpacerItem(466, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_main.addItem(spacerItem2)
        self.horizontalLayout_question = QtWidgets.QHBoxLayout()
        self.horizontalLayout_question.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout_question.setObjectName("horizontalLayout_question")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_question.addItem(spacerItem3)
        self.label_question = QtWidgets.QLabel(Dialog_deleteProject)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_question.sizePolicy().hasHeightForWidth())
        self.label_question.setSizePolicy(sizePolicy)
        self.label_question.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label_question.setObjectName("label_question")
        self.horizontalLayout_question.addWidget(self.label_question)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_question.addItem(spacerItem4)
        self.verticalLayout_main.addLayout(self.horizontalLayout_question)
        spacerItem5 = QtWidgets.QSpacerItem(466, 13, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_main.addItem(spacerItem5)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem6)
        self.pushButton_yes = QtWidgets.QPushButton(Dialog_deleteProject)
        self.pushButton_yes.setObjectName("pushButton_yes")
        self.horizontalLayout_buttons.addWidget(self.pushButton_yes)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem7)
        self.pushButton_no = QtWidgets.QPushButton(Dialog_deleteProject)
        self.pushButton_no.setObjectName("pushButton_no")
        self.horizontalLayout_buttons.addWidget(self.pushButton_no)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_buttons.addItem(spacerItem8)
        self.horizontalLayout_buttons.setStretch(0, 1)
        self.horizontalLayout_buttons.setStretch(4, 1)
        self.verticalLayout_main.addLayout(self.horizontalLayout_buttons)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_main.addItem(spacerItem9)
        self.verticalLayout_main.setStretch(5, 2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_main)

        self.retranslateUi(Dialog_deleteProject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_deleteProject)

    def retranslateUi(self, Dialog_deleteProject):
        _translate = QtCore.QCoreApplication.translate
        Dialog_deleteProject.setWindowTitle(_translate("Dialog_deleteProject", "Delete Project?"))
        self.label_question.setText(_translate("Dialog_deleteProject", "Do you really want to delete this project?"))
        self.pushButton_yes.setText(_translate("Dialog_deleteProject", "Yes"))
        self.pushButton_no.setText(_translate("Dialog_deleteProject", "No"))
