# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Documents\Programmation\PublicProject\checkFrench\qt\dialog_excluded_words\dialog_excluded_words.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(548, 609)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ressource/DreamteamLogo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setSizeGripEnabled(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 11)
        self.verticalLayout.setSpacing(37)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget_excludedWords = QtWidgets.QTableWidget(Dialog)
        self.tableWidget_excludedWords.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.tableWidget_excludedWords.setDragDropOverwriteMode(False)
        self.tableWidget_excludedWords.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_excludedWords.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableWidget_excludedWords.setObjectName("tableWidget_excludedWords")
        self.tableWidget_excludedWords.setColumnCount(1)
        self.tableWidget_excludedWords.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_excludedWords.setHorizontalHeaderItem(0, item)
        self.tableWidget_excludedWords.horizontalHeader().setVisible(False)
        self.tableWidget_excludedWords.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget_excludedWords.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_excludedWords.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.tableWidget_excludedWords)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 14, -1)
        self.horizontalLayout.setSpacing(13)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_resetChange = QtWidgets.QPushButton(Dialog)
        self.pushButton_resetChange.setMinimumSize(QtCore.QSize(140, 41))
        self.pushButton_resetChange.setAutoDefault(False)
        self.pushButton_resetChange.setObjectName("pushButton_resetChange")
        self.horizontalLayout.addWidget(self.pushButton_resetChange)
        self.pushButton_saveAndQuit = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_saveAndQuit.sizePolicy().hasHeightForWidth())
        self.pushButton_saveAndQuit.setSizePolicy(sizePolicy)
        self.pushButton_saveAndQuit.setMinimumSize(QtCore.QSize(140, 41))
        self.pushButton_saveAndQuit.setAutoDefault(False)
        self.pushButton_saveAndQuit.setObjectName("pushButton_saveAndQuit")
        self.horizontalLayout.addWidget(self.pushButton_saveAndQuit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "DreamTeamTrad - FautesCheck - Liste mots exclus"))
        item = self.tableWidget_excludedWords.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "mots"))
        self.pushButton_resetChange.setText(_translate("Dialog", "Réinitialiser changements"))
        self.pushButton_saveAndQuit.setText(_translate("Dialog", "Sauvegarder et quitter"))
import qt.ressource_rc
